# 允许 QQ 调用系统的 D-Bus（用于唤起外部浏览器打开链接、调用系统文件管理器）
--bind /run/user/$(id -u)/bus /run/user/$(id -u)/bus

# 允许访问下载目录，方便接收和发送文件
--bind ${HOME}/Downloads/QQ ${HOME}/Downloads/QQ

# 如果你使用的是暗色模式，允许它读取 GTK 配置
--ro-bind-try ${HOME}/.config/gtk-3.0 ${HOME}/.config/gtk-3.0
--ro-bind-try ${HOME}/.config/gtk-4.0 ${HOME}/.config/gtk-4.0

# 解决部分文件管理器无法从 QQ 打开目录的问题
--bind /run/user/$(id -u) run/user/$(id -u)
